spring:
  datasource:
#    platform: h2
    url: jdbc:h2:mem:testdb
    initialization-mode: always #
#    schema: schema.sql
#    data: data.sql

  jpa:
    generate-ddl: false # execute schema.sql
    hibernate:
      ddl-auto: none #create #validate #генерировать ddl по аннотациям на классах/полях

    properties:
      hibernate:
        format_sql: true

    show-sql: true


logging:
  level:
    ROOT: ERROR


#spring:
#  datasource:
#    initialization-mode: always
#    schema: schema.sql
#    data: data.sql