drop table authors if exists;
drop table book_author_links if exists;
drop table book_comments if exists;
drop table books if exists;
drop table genres if exists;

create table authors (
   id bigint generated by default as identity,
    first_name varchar(255) not null,
    second_name varchar(255) not null,
    primary key (id)
);

create table book_author_links (
   book_id bigint not null,
    author_id bigint not null
);

create table book_comments (
   id bigint generated by default as identity,
    comment varchar(255) not null,
    book_id bigint not null,
    primary key (id)
);

create table books (
   id bigint generated by default as identity,
    name varchar(255) not null,
    genre_id bigint not null,
    primary key (id)
);

create table genres (
   id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

alter table books
   add constraint UK_books_name unique (name);

alter table genres
   add constraint UK_genres_name unique (name);

alter table book_author_links
   add constraint FKn08d5petvk7irdkwx7gckkmsd
   foreign key (author_id)
   references authors;

alter table book_author_links
   add constraint FKg5o7k312xo17um2f8p9rb20h9
   foreign key (book_id)
   references books;

alter table book_comments
   add constraint FK6xpmpddanwk8vq96sax69c4hu
   foreign key (book_id)
   references books;

alter table books
   add constraint FK9hsvoalyniowgt8fbufidqj3x
   foreign key (genre_id)
   references genres;